server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dexterlab?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  # REDIS
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址 （默认为127.0.0.1）
    port: 6379 # Redis服务器连接端口 （默认为6379）
    password: # Redis服务器连接密码（默认为空）
    timeout: 2000 # 连接超时时间（毫秒）

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  typeAliasesPackage: com.dexterlab.crm.domain.entity
logging:
  level:
    com:
      dexterlab: DEBUG
